### ISSUE TITLE
feat: add a feature to load configuration from environment variable

### ISSUE THREAD

**Issue by aqyuki** [aqyuki/fav-archive#9]
# Task
- [ ] Add a feature to load configuration from environment variable.
- [ ] Add a feature to save configuration to structure.
- [ ] Add some tests
